#define JUMP_X 6
#define JUMP_Y 3
#define CORR_COEFFICIENT_THRESHOLD 0.5
#define MEAN_THRESHOLD 90
#define MORPH_DILATION_FILTER 13
#define BINARY_IMAGE_THRESHOLD 40.00
#define CAR_TEMPLATE_NAME "Templates/template-car"
#define HOG_CELL_SIZE 8
#define HOG_BIN_SIZE 9
#define HOG_BIN_SEPERATION 20                                                                                                                                            
#define HOG_BLOCK_SIZE 2
#define PI 3.14159265
#define NUMBER_OF_TEMPLATES 2
